import type { Story } from "./types";

/**
 * The story the channel opens on.
 *
 * A rolling channel has no beginning, which is a problem the first time someone
 * watches it: they arrive mid-block, mid-subject, with no idea what they are
 * looking at. A pinned lead gives the opening block a front door, and the
 * honest thing to open on is what the channel is running on.
 *
 * Everything asserted here is checkable. Reactor hosts the model as `fast-h3`
 * and this channel is generated by it; H3 is MiniMax's open-weight omni-modal
 * model, released on 31 July 2026, generating video with native stereo audio;
 * the rate comes from Reactor's own pricing endpoint. Reactor's docs do not
 * themselves state the MiniMax attribution, so nothing here claims they do —
 * and nothing here invents a quote, a date or a figure.
 */
export const PINNED_LEAD: Story = {
  id: "pinned:reactor-fast-h3-minimax",
  title: "Reactor adds MiniMax H3, the model generating this bulletin",
  summary:
    "Reactor now serves MiniMax's H3 as fast-h3, an open-weight model that generates picture and sound in a single pass rather than dubbing audio on afterwards. H3 was released on 31 July 2026 and produces clips of up to fifteen seconds with native stereo audio. Reactor bills it at seventy credits a second. This channel — the anchor, the correspondents and the cutaways — is generated on it live.",
  source: "R24",
  category: "technology",
  link: "https://reactor.inc",
  publishedAt: Date.now(),
  live: true,
};
